### ISSUE TITLE
聊天栏超链接文本点击无效

### ISSUE THREAD

**Issue by CottonCandy2004** [Lazy-Bing-Server/THB-MCDR#4]
聊天栏超链接文本点击无效，只能通过输入tpa同意
minecraft版本：1.20.1
MCDReforged version: 2.13.2
LazyBing THB (lazybing_thb@1.0.1)

**Comment by Ra1ny-Yuki** [comment]
Minecraft 修改了点击事件逻辑，见 MCDReforged/MCDReforged#203
